-- 
-- Patch for mod https://steamcommunity.com/sharedfiles/filedetails/?id=2313387159 better sorting
-- 
if getActivatedMods():contains("BetterSortCC") then
    local function setDisplayCategory(itemName, category)
        ScriptManager.instance:getItem(itemName):DoParam("DisplayCategory = " .. category)
    end
    -- Выживание - Фермерство   СЕМЕНА/ПАЧКИ СЕМЯН
    setDisplayCategory("SHF.Appleseed", "SurFarm")
    setDisplayCategory("SHF.Bananaseed", "SurFarm")
    setDisplayCategory("SHF.BerryBlackseed", "SurFarm")
    setDisplayCategory("SHF.BerryBlueseed", "SurFarm")
    setDisplayCategory("SHF.Cherryseed", "SurFarm")
    setDisplayCategory("SHF.Grapefruitseed", "SurFarm")
    setDisplayCategory("SHF.Grapesseed", "SurFarm")
    setDisplayCategory("SHF.Lemonseed", "SurFarm")
    setDisplayCategory("SHF.Limeseed", "SurFarm")
    setDisplayCategory("SHF.Mangoseed", "SurFarm")
    setDisplayCategory("SHF.Orangeseed", "SurFarm")
    setDisplayCategory("SHF.Peachseed", "SurFarm")
    setDisplayCategory("SHF.Pearseed", "SurFarm")
    setDisplayCategory("SHF.Pineappleseed", "SurFarm")
    setDisplayCategory("SHF.Avocadoseed", "SurFarm")
    setDisplayCategory("SHF.Cornseed", "SurFarm")
    setDisplayCategory("SHF.Eggplantseed", "SurFarm")
    setDisplayCategory("SHF.Leekseed", "SurFarm")
    setDisplayCategory("SHF.Lettuceseed", "SurFarm")
    setDisplayCategory("SHF.Onionseed", "SurFarm")
    setDisplayCategory("SHF.Pepperseed", "SurFarm")
    setDisplayCategory("SHF.Watermelonseed", "SurFarm")
    setDisplayCategory("SHF.Zucchiniseed", "SurFarm")
    setDisplayCategory("SHF.Teaseed", "SurFarm")
    setDisplayCategory("SHF.Coffeeseed", "SurFarm")
    
    setDisplayCategory("SHF.AppleBagSeed", "SurFarm")
    setDisplayCategory("SHF.BananaBagSeed", "SurFarm")
    setDisplayCategory("SHF.BerryBlackBagSeed", "SurFarm")
    setDisplayCategory("SHF.BerryBlueBagSeed", "SurFarm")
    setDisplayCategory("SHF.CherryBagSeed", "SurFarm")
    setDisplayCategory("SHF.GrapefruitBagSeed", "SurFarm")
    setDisplayCategory("SHF.GrapesBagSeed", "SurFarm")
    setDisplayCategory("SHF.LemonBagSeed", "SurFarm")
    setDisplayCategory("SHF.LimeBagSeed", "SurFarm")
    setDisplayCategory("SHF.MangoBagSeed", "SurFarm")
    setDisplayCategory("SHF.OrangeBagSeed", "SurFarm")
    setDisplayCategory("SHF.PeachBagSeed", "SurFarm")
    setDisplayCategory("SHF.PearBagSeed", "SurFarm")
    setDisplayCategory("SHF.PineappleBagSeed", "SurFarm")
    setDisplayCategory("SHF.AvocadoBagSeed", "SurFarm")
    setDisplayCategory("SHF.CornBagSeed", "SurFarm")
    setDisplayCategory("SHF.EggplantBagSeed", "SurFarm")
    setDisplayCategory("SHF.LeekBagSeed", "SurFarm")
    setDisplayCategory("SHF.LettuceBagSeed", "SurFarm")
    setDisplayCategory("SHF.OnionBagSeed", "SurFarm")
    setDisplayCategory("SHF.PepperBagSeed", "SurFarm")
    setDisplayCategory("SHF.WatermelonBagSeed", "SurFarm")
    setDisplayCategory("SHF.ZucchiniBagSeed", "SurFarm")
    setDisplayCategory("SHF.TeaBagSeed", "SurFarm")
    setDisplayCategory("SHF.CoffeeBagSeed", "SurFarm")

    -- Еда
    setDisplayCategory("SHF.TeaLeaves", "FoodP")
    setDisplayCategory("SHF.CoffeeBeans", "FoodP")
    setDisplayCategory("SHF.CoffeeBeansRoasted", "FoodP")
    setDisplayCategory("SHF.SunFlower", "FoodP")
    setDisplayCategory("SHF.WheatGrain", "FoodP")
    setDisplayCategory("SHF.Wheat", "FoodP")

end